# Generated by Django 2.1.7 on 2019-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogame', '0002_auto_20190303_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
