# Generated by Django 2.1.7 on 2019-03-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogame', '0003_auto_20190303_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangogame.School'),
        ),
    ]
